# Generated by Django 5.1.1 on 2025-03-18 21:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=15,
                verbose_name="الجنس",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True, verbose_name="رقم الهاتف"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Employee", "Employee"),
                    ("Parent", "Parent"),
                ],
                default="Admin",
                max_length=15,
                verbose_name="الدور",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الحساب",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_name",
            field=models.CharField(max_length=150, verbose_name="جهة اتصال الطوارئ"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="رقم اتصال الطوارئ"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="join_date",
            field=models.DateField(verbose_name="تاريخ الانضمام"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="resignation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الاستقالة"
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parent_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الحساب",
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="address",
            field=models.CharField(max_length=255, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="parent",
            name="nationality",
            field=models.CharField(max_length=50, verbose_name="الجنسية"),
        ),
        migrations.AlterField(
            model_name="parent",
            name="work_phone",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="هاتف العمل"
            ),
        ),
    ]
