# Generated by Django 5.1.2 on 2024-10-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('First Play', 'First Play'), ('Second Play', 'Second Play'), ('Third Play', 'Third Play'), ('First Art', 'First Art'), ('Second Art', 'Second Art'), ('Third Art', 'Third Art')], max_length=20, unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours_stayed', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('number_of_art_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('hours_deducted_from_card', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('total_purchased_items', models.IntegerField(default=0)),
                ('total_hours_due', models.IntegerField(blank=True, null=True)),
                ('total_amount_to_receive', models.IntegerField(blank=True, null=True)),
                ('bringer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children_bringed', to='child.relationship')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='child.child')),
                ('employee_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children_entered', to='account.employee')),
                ('employee_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_exited', to='account.employee')),
                ('taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_taken', to='child.relationship')),
            ],
        ),
    ]
