# Generated by Django 5.1.1 on 2025-03-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_account_gender_alter_account_phone_number_and_more"),
        ("attendance", "0001_initial"),
        ("child", "0003_alter_child_address_alter_child_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="bringer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children_bringed",
                to="child.relationship",
                verbose_name="محضر الطفل",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="child.child",
                verbose_name="الطفل",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="التاريخ"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee_in",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children_entered",
                to="account.employee",
                verbose_name="الموظف المستلم",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee_out",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children_exited",
                to="account.employee",
                verbose_name="المسلم",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="entry_time",
            field=models.DateTimeField(verbose_name="وقت الدخول"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="exit_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت الخروج"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="hours_deducted_from_card",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                verbose_name="عدد الساعات المخصومة من البطاقة",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="number_of_art_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                verbose_name="ساعات الفنون",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="taker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children_taken",
                to="child.relationship",
                verbose_name="آخذ الطفل",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_amount_to_receive",
            field=models.IntegerField(blank=True, null=True, verbose_name="الاجمالي"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_hours_due",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="مجموع الساعات"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_hours_stayed",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                verbose_name="اجمالي الساعات",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_purchased_items",
            field=models.IntegerField(default=0, verbose_name="مجموع المشتريات"),
        ),
        migrations.AlterField(
            model_name="hourpricing",
            name="price",
            field=models.IntegerField(verbose_name="السعر"),
        ),
        migrations.AlterField(
            model_name="hourpricing",
            name="rank",
            field=models.CharField(
                choices=[
                    ("First Play", "First Play"),
                    ("Second Play", "Second Play"),
                    ("Third Play", "Third Play"),
                    ("First Art", "First Art"),
                    ("Second Art", "Second Art"),
                    ("Third Art", "Third Art"),
                ],
                max_length=20,
                unique=True,
                verbose_name="ترتيب الساعة",
            ),
        ),
    ]
