# Generated by Django 5.1.2 on 2024-10-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoldItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_items', to='attendance.attendance')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold', to='market.marketitem')),
            ],
        ),
    ]
