# Generated by Django 5.1.1 on 2025-03-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_alter_attendance_bringer_alter_attendance_child_and_more"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketitem",
            name="name",
            field=models.CharField(max_length=150, verbose_name="اسم المادة"),
        ),
        migrations.AlterField(
            model_name="marketitem",
            name="price",
            field=models.IntegerField(verbose_name="السعر"),
        ),
        migrations.AlterField(
            model_name="marketitem",
            name="quantity",
            field=models.IntegerField(verbose_name="الكمية"),
        ),
        migrations.AlterField(
            model_name="solditems",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchased_items",
                to="attendance.attendance",
                verbose_name="الحضور",
            ),
        ),
        migrations.AlterField(
            model_name="solditems",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sold",
                to="market.marketitem",
                verbose_name="المادة",
            ),
        ),
        migrations.AlterField(
            model_name="solditems",
            name="notes",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="ملاحظات"
            ),
        ),
        migrations.AlterField(
            model_name="solditems",
            name="quantity_sold",
            field=models.IntegerField(verbose_name="الكمية"),
        ),
        migrations.AlterField(
            model_name="solditems",
            name="selling_price",
            field=models.IntegerField(verbose_name="السعر الافردي"),
        ),
    ]
