# Generated by Django 5.1.2 on 2024-10-28 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='account.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GRAND_FATHER', 'Grand Father'), ('GRAND_MOTHER', 'Grand Mother'), ('COUSINE', 'Cousine'), ('AUNT', 'Aunt'), ('UNCLE', 'Uncle')], max_length=50)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatives', to='child.child')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
