# Generated by Django 5.1.1 on 2025-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("child", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="school",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
