# Generated by Django 5.1.1 on 2025-03-18 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_account_gender_alter_account_phone_number_and_more"),
        ("child", "0002_alter_child_notes_alter_child_school"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="address",
            field=models.CharField(max_length=255, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="child",
            name="date_of_birth",
            field=models.DateField(verbose_name="تاريخ الميلاد"),
        ),
        migrations.AlterField(
            model_name="child",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="الاسم الاول"),
        ),
        migrations.AlterField(
            model_name="child",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=10,
                verbose_name="الجنس",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="الاسم الاخير"),
        ),
        migrations.AlterField(
            model_name="child",
            name="notes",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ملاحظات"
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="account.parent",
                verbose_name="الأب أو الأم",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="school",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="المدرسة"
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relatives",
                to="child.child",
                verbose_name="الطفل",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("FATHER", "Father"),
                    ("MOTHER", "Mother"),
                    ("GRAND_FATHER", "Grand Father"),
                    ("GRAND_MOTHER", "Grand Mother"),
                    ("COUSINE", "Cousine"),
                    ("AUNT", "Aunt"),
                    ("UNCLE", "Uncle"),
                ],
                max_length=50,
                verbose_name="صلة القرابة بالنسبة للطفل",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="relative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relatives",
                to=settings.AUTH_USER_MODEL,
                verbose_name="القريب",
            ),
        ),
    ]
