# Generated by Django 5.1.2 on 2024-10-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('ART', 'Art'), ('PLAY', 'Play')], max_length=15)),
                ('validity_days', models.IntegerField()),
                ('validity_hours', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SoldCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('remaining_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.card')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='account.parent')),
            ],
            options={
                'ordering': ['-sold_date'],
            },
        ),
        migrations.CreateModel(
            name='CardConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_consumed_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_consumptions', to='attendance.attendance')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_consumptions', to='card.soldcards')),
            ],
        ),
    ]
