# Generated by Django 5.1.1 on 2025-03-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_account_gender_alter_account_phone_number_and_more"),
        ("attendance", "0002_alter_attendance_bringer_alter_attendance_child_and_more"),
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="color",
            field=models.CharField(max_length=15, verbose_name="اللون"),
        ),
        migrations.AlterField(
            model_name="card",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="السعر"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="type",
            field=models.CharField(
                choices=[("ART", "Art"), ("PLAY", "Play")],
                max_length=15,
                verbose_name="النوع",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="validity_days",
            field=models.IntegerField(verbose_name="عدد الايام"),
        ),
        migrations.AlterField(
            model_name="card",
            name="validity_hours",
            field=models.IntegerField(verbose_name="عدد الساعات"),
        ),
        migrations.AlterField(
            model_name="cardconsumption",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="card_consumptions",
                to="attendance.attendance",
                verbose_name="الحضور",
            ),
        ),
        migrations.AlterField(
            model_name="cardconsumption",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="card_consumptions",
                to="card.soldcards",
                verbose_name="البطاقة",
            ),
        ),
        migrations.AlterField(
            model_name="cardconsumption",
            name="number_of_consumed_hours",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="عدد الساعات المخصومة"
            ),
        ),
        migrations.AlterField(
            model_name="soldcards",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="card.card",
                verbose_name="البطاقة",
            ),
        ),
        migrations.AlterField(
            model_name="soldcards",
            name="expiry_date",
            field=models.DateField(verbose_name="تاريخ الانتهاء"),
        ),
        migrations.AlterField(
            model_name="soldcards",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="account.parent",
                verbose_name="الأب",
            ),
        ),
        migrations.AlterField(
            model_name="soldcards",
            name="remaining_hours",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="الساعات المتبقية"
            ),
        ),
        migrations.AlterField(
            model_name="soldcards",
            name="sold_date",
            field=models.DateField(auto_now_add=True, verbose_name="تاريخ الشراء"),
        ),
    ]
